services:
  ##################################
  # MongoDB Backing Service
  ##################################
  mongodb:
    image: mongo:7.0.5
    ports:
      - 27017:27017
    extra_hosts:
      - "mongodb:127.0.0.1"
    healthcheck:
      test: echo "db.runCommand('ping')" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      retries: 3
    command: ["--bind_ip_all", "--port", "27017"]
    profiles:
      - dev
      - deploy

  ##################################
  # MongoDB Configurator API - Dev Mode (mounts ./configurator to /input)
  ##################################
  dev_api:
    image: ghcr.io/agile-learning-institute/mongodb_configurator_api:latest
    restart: no
    ports:
      - 8081:8081
    environment:
      MONGO_CONNECTION_STRING: mongodb://mongodb:27017/
      AUTO_PROCESS: False
      LOAD_TEST_DATA: True
      MONGO_DB_NAME: test_database
      API_PORT: 8081
      SPA_PORT: 8082
      MONGODB_REQUIRE_TLS: False
    volumes:
      - ./configurator:/input
    depends_on:
      mongodb:
        condition: service_healthy
    profiles:
      - dev

  dev_spa:
    image: ghcr.io/agile-learning-institute/mongodb_configurator_spa:latest
    restart: no
    environment:
      API_HOST: dev_api
      API_PORT: 8081
      SPA_PORT: 8082
    ports:
      - 8082:8082
    depends_on:
      dev_api:
        condition: service_started
    profiles:
      - dev

  ##################################
  # MongoDB Configurator API - Deploy Mode (Packaged Configurations)
  ##################################
  deploy_api:
    image: YOUR_ORGANIZATION/mongodb_api:latest
    restart: no
    ports:
      - 8081:8081
    environment:
      MONGO_CONNECTION_STRING: mongodb://mongodb:27017/
      AUTO_PROCESS: False
      LOAD_TEST_DATA: True
      MONGO_DB_NAME: test_database
      API_PORT: 8081
      SPA_PORT: 8082
      MONGODB_REQUIRE_TLS: False
    depends_on:
      mongodb:
        condition: service_healthy
    profiles:
      - deploy

  deploy_spa:
    image: ghcr.io/agile-learning-institute/mongodb_configurator_spa:latest
    restart: no
    environment:
      API_HOST: deploy_api
      API_PORT: 8081
      SPA_PORT: 8082
    ports:
      - 8082:8082
    depends_on:
      deploy_api:
        condition: service_started
    profiles:
      - deploy

